package tabletop;

public enum Language {
	COMMON,	DWARVISH, ELVISH, GIANT, GNOMISH, GOBLIN, HALFLING, ORC,
	ABYSSAL, CELESTIAL, DRACONIC, DEEP_SPEECH, INFERNAL, PRIMORDIAL,
	SYLVAN, UNDERCOMMON	
}
